name: jellyflut
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.16

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player:
    git:
      url: https://github.com/markst/Flutter-AssetsAudioPlayer
      ref: master
  better_player: ^0.0.61
  cached_network_image: ^2.5.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.0
  device_info: ^0.4.2+10
  dio: ^3.0.10
  ext_storage: ^1.0.3
  fereader: ^0.2.0
  flutter_svg: ^0.19.1
  flutter_vlc_player: ^5.0.4
  fluttertoast: ^7.1.6
  octo_image: ^0.3.0
  package_info: ^0.4.3+4
  palette_generator: ^0.2.3
  permission_handler: ^5.0.1+1
  provider: ^4.3.3
  settings_ui: ^0.6.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  splashscreen: ^1.3.5
  sqflite: ^1.3.2+3
  sqflite_common_ffi: ^1.1.1+3
  uuid: ^2.2.2
  wakelock: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.0
  # intl: ^0.16.1
  pedantic: ^1.9.2

# The following section is specific to Flutter.
flutter:
  assets:
    - img/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
