name: jellyflut
description: Jellyfin client made with Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.55

environment:
  sdk: ">=2.12.0 <3.0.0"

module:
  androidX: true

dependencies:
  archive: ^3.1.6
  audio_video_progress_bar: ^0.10.0
  auto_route: ^3.1.3
  better_player: ^0.0.79
  bloc: ^7.2.1
  blurhash_dart: ^1.1.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  dart_vlc: ^0.1.8
  device_info_plus: ^3.1.1
  dio: ^4.0.4
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  epubx: ^3.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_colorpicker: ^1.0.2
  flutter_html: ^2.2.0
  flutter_svg: ^0.23.0+1
  flutter_vlc_player: ^6.0.5
  fluttertoast: ^8.0.8
  just_audio: ^0.9.18
  just_audio_libwinmedia: ^0.0.4
  moor: ^4.6.1+1
  octo_image: ^1.0.0+1
  package_info_plus: ^1.3.0
  palette_generator: ^0.3.2
  path: ^1.8.0
  path_provider: ^2.0.7
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  provider: ^6.0.1
  reactive_forms: ^10.6.5
  responsive_builder:
    git:
      url: git://github.com/georgeherby/responsive_builder.git
      ref: master
  rxdart: ^0.27.3
  salomon_bottom_bar: ^3.1.0
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.9
  shimmer: ^2.0.0
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
  sqlite3_flutter_libs: ^0.5.1
  url_launcher: ^6.0.16
  uuid: ^3.0.5
  wakelock: ^0.5.6
  window_manager: ^0.1.1
  youtube_explode_dart: ^1.10.8

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  moor_generator: ^4.6.0+1
  pedantic: ^1.11.1

# dependency_overrides:
# The following section is specific to Flutter.
flutter:
  assets:
    - img/
    - translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          style: normal
    - family: HindMadurai
      fonts:
        - asset: fonts/HindMadurai-Regular.ttf
          style: normal
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
          style: normal

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
