name: jellyflut
description: Jellyfin client made with Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.55

environment:
  sdk: ">=2.12.0 <3.0.0"

module:
  androidX: true

dependencies:
  archive: ^3.1.2
  assets_audio_player: ^3.0.3+6
  audio_video_progress_bar: ^0.9.0
  auto_route: ^2.3.0
  auto_size_text: ^3.0.0-nullsafety.0
  better_player: ^0.0.73
  bloc: ^7.1.0
  blurhash_dart: ^1.0.2
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  dart_vlc: ^0.1.7
  device_info_plus: ^2.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  epubx: ^3.0.0-dev.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_colorpicker: ^0.6.0
  flutter_html: ^2.1.2
  flutter_svg: ^0.22.0
  flutter_vlc_player: ^6.0.3
  fluttertoast: ^8.0.8
  marquee: ^2.2.0
  moor: ^4.4.1
  octo_image: ^1.0.0+1
  package_info_plus: ^1.0.6
  palette_generator: ^0.3.0
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  photo_view: ^0.12.0
  provider: ^6.0.0
  reactive_forms: ^10.6.0
  responsive_builder: ^0.4.1
  rxdart: ^0.27.1
  salomon_bottom_bar: ^3.1.0
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.0.10
  uuid: ^3.0.4
  wakelock: ^0.5.3+3
  window_manager: ^0.0.3
  youtube_explode_dart: ^1.10.4

dev_dependencies:
  auto_route_generator: ^2.3.0
  build_runner: ^2.0.6
  flutter_launcher_icons:
    git:
      url: git://github.com/SimonIT/flutter_launcher_icons.git
      ref: scaling
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  moor_generator: ^4.4.1
  pedantic: ^1.11.1

dependency_overrides:
  args: ^2.1.1

# The following section is specific to Flutter.
flutter:
  assets:
    - img/
    - translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          style: normal
    - family: HindMadurai
      fonts:
        - asset: fonts/HindMadurai-Regular.ttf
          style: normal
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
          style: normal

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
