name: jellyflut
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.20

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.0.3+5
  better_player: ^0.0.72
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  dio: ^4.0.0
  epub_viewer: ^0.2.2
  ext_storage: ^1.0.3
  flutter_svg: ^0.22.0
  flutter_vlc_player: ^6.0.2
  fluttertoast: ^8.0.7
  moor: ^4.4.1
  octo_image: ^1.0.0+1
  package_info: ^2.0.2
  palette_generator: ^0.3.0
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.3
  photo_view: ^0.12.0
  provider: ^5.0.0
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  splashscreen: ^1.3.5
  sqlite3_flutter_libs: ^0.5.0
  uuid: ^3.0.4
  wakelock: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  # flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0
  intl: ^0.17.0
  moor_generator: ^4.4.1
  pedantic: ^1.11.1

# The following section is specific to Flutter.
flutter:
  assets:
    - img/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
