name: items_api
description: A dart API client for the Jellyfin Item API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  jellyflut_models:
    path: ../../jellyflut_models

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  pedantic: ^1.11.1
