name: Main workflow
on: push

env:
  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  ALIAS: ${{ secrets.ALIAS }}
  KEY_PATH: key.jks

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .

  build:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'main')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - run: echo $ANDROID_KEYS | base64 -d > android/app/key.jks
      env:
        ANDROID_KEYS: ${{ secrets.ANDROID_KEYS }}

    - run: flutter build apk --debug          # debug
    - run: flutter build apk --profile        # profile
    - run: flutter build apk --split-per-abi  # release (per arch)

    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
    